name: Deploy Astro to GitHub Pages (prod branch)

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

      - name: Add .nojekyll to prevent GitHub Pages from using Jekyll
        run: touch dist/.nojekyll

      - name: Deploy to prod branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: prod
